version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
